### ISSUE TITLE
How clusters can stay open all the time ?

### ISSUE THREAD

**Issue by doctor343434** [ghybs/Leaflet.MarkerCluster.Freezable#15]
when clustering is clicked, previous clustering closes, how can I solve this?
How can I keep it open, no matter which cluster is clicked?
Thank you !

![image](https://user-images.githubusercontent.com/62885102/87400683-cbfdf680-c5c1-11ea-9534-3b5c7fd04331.png)

**Comment by ghybs** [comment]
Hi,

This is a known design limitation of Leaflet.markercluster.
See https://github.com/Leaflet/Leaflet.markercluster/issues/101 and https://github.com/Leaflet/Leaflet.markercluster/issues/744

If you really need this feature, consider contributing to Leaflet.markercluster. See the related issues, as it looks like several people where keen to do so.
