### ISSUE TITLE
Support for new Leaflet (1.6) versions? 

### ISSUE THREAD

**Issue by do-me** [ghybs/Leaflet.MarkerCluster.Freezable#16]
Great plugin! 
Could newer Leaflet versions also be supported?

**Comment by ghybs** [comment]
Hi @do-me,

Thank you for your feedback!

Do you mean there is something broken in this plugin since Leaflet 1.6?
If so, please can you kindly provide a reproduction example, e.g. using Plunker / JSFiddle / etc.?

Thank you!

**Comment by do-me** [comment]
I load a lot of stuff via CDN, but also get this error message without the additional scripts right away:
```
leaflet.markercluster.freezable.js:6 Uncaught TypeError: Cannot read property 'include' of undefined
    at leaflet.markercluster.freezable.js:6
    at leaflet.markercluster.freezable.js:6
    at leaflet.markercluster.freezable.js:6
```
Plunker: https://plnkr.co/edit/89MT3oo89G6XX5L9?open=lib/script.js (click on index.html, preview)

**Comment by ghybs** [comment]
The `leaflet.markercluster.js` script must be loaded **before** this plugin.

**Comment by do-me** [comment]
Changed the order but still not working when calling i.e. `disableClustering() `or am I getting something wrong? https://plnkr.co/edit/mBc8I0ZHHrv9yOEX?open=lib%2Fscript.js

**Comment by ghybs** [comment]
Works for me: https://plnkr.co/edit/2VdXwgH6T8767Ayy?preview

**Comment by do-me** [comment]
Don't ask why but for some reason I thought `disableClustering()` could be called globally and would disable clustering for all layers. `markers.disableClustering()` worked! Sorry for wasting your time but thanks a lot for your help!
