### ISSUE TITLE
Compatibility with leaflet-1.0.0?

### ISSUE THREAD

**Issue by fpauser** [ghybs/Leaflet.MarkerCluster.Freezable#3]
I use it without problems with leaflet-1.0.0 and Leaflet.markerCluster. Is leaflet-1.0.0 compatibility official?
If so we should update the README.

**Comment by ghybs** [comment]
Hi,

Thank you for your confirmation that in your case, everything looks to work fine with Leaflet 1.0.0 and MCG 1.0.0!

The code of this plugin is rather simple, so indeed there is a high chance that it is not affected by the changes that occurred in Leaflet (from 0.7.7) and MCG (from 0.5.0).

Still, we would probably need to make a few tests, whether manually or automated, before claiming the new compatibility.

**Comment by ghybs** [comment]
Done.

Also took the opportunity to add the minified version, and publish to npm:
https://www.npmjs.com/package/leaflet.markercluster.freezable

**Comment by fpauser** [comment]
Great - thanks!
