### ISSUE TITLE
disableClustering() Removes Existing Unclustered Markers

### ISSUE THREAD

**Issue by TheCrabity** [ghybs/Leaflet.MarkerCluster.Freezable#5]
Performing a disableClustering() on a layer that has markers already unclustered, causes those markers to be removed from the feature group of that layer and only the newly unclustered ones to be visible. Panning the view slightly restores these removed markers back to the map.

**Comment by ghybs** [comment]
Hi,

Thank you for your message.

Please can you provide a live reproduction example of the behaviour you describe?
You can use for example the Leaflet [playground](http://playground-leaflet.rhcloud.com/), Plunker, JSFiddle, etc.

I cannot reproduce on the [live demo](http://ghybs.github.io/Leaflet.MarkerCluster.Freezable/examples/mcg-freezable-leaflet1.0.0.html) of this plugin.

Thank you.

**Comment by TheCrabity** [comment]
Heya,

If you give me an email or some way to send you the login info in private, happy to show/debug with you. Do you have discord or skype?

**Comment by ghybs** [comment]
Ok I have been able to reproduce the bug.
This is a compatibility issue with Leaflet.markercluster 1.0.4+

That version introduces a new argument in `L.MarkerCluster` private method `_recursivelyRemoveChildrenFromMap`
https://github.com/Leaflet/Leaflet.markercluster/commit/162f15722e9d0e5ae576813ea8ac8f6a78617fc4#diff-f597262ff05b9a7417f2b3bd8b8961afL333

Freezable sub-plugin uses that private method, therefore it requires being updated to the new signature.
