### ISSUE TITLE
Markers disapear when adding them to a freezable group

### ISSUE THREAD

**Issue by MaciejKus** [ghybs/Leaflet.MarkerCluster.Freezable#7]
I made a leaflet playground here:
http://playground-leaflet.rhcloud.com/bilav/1/edit?html,output

What I am doing is moving some markers between a regular cluster group and a freezable cluster group. I am doing this to make some individual markers not cluster sometimes. 

I find that any marker that exists outside of the original view/zoom of the map disappears when I first add it to the frozen group. Panning the map or changing the zoom makes the markers appear as expected.

**Comment by ghybs** [comment]
Hi,

Thank you for the detailed report including the playground!

Hum indeed it looks like the internal `_currentShownBounds` are not updated when the map view changes (zoom and/or pan), which makes the MCG not showing markers which are dynamically added outside of the "initial" view (i.e. the current view when MCG is frozen).
But it behaves normally when "manually" zooming and/or panning, only newly added markers are affected by this bug.

The fix looks easy then, just update that internal cache as well, which is indeed a step that is included in Leaflet.markercluster's `_moveend` but for some reason missing in freezable's `_viewChangeEndNotClustering`

Updated playground: http://playground-leaflet.rhcloud.com/muxi/1/edit?html,console,output
